import os

import cognitojwt
from dotenv import load_dotenv
load_dotenv()

os.environ.get('COGNITO_REGION_NAME')

id_token = 'ayJraWQiOiJcL0Fia01US1h1UitIVmtsb0N2SE1PdVJ0NXJZZStvY1VxRThFNEJMeVNBdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI5ODdjMmM3ZC0xNjBiLTQzMWYtYTMwNy00NTQ2ZjJjMTFmZjQiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9aaEhESllMNWMiLCJjbGllbnRfaWQiOiIybmx2NGdvMWpjMWE3ajV1ZXFiNWsxcnYxaSIsIm9yaWdpbl9qdGkiOiIzNmIwMWU0My1jMDEyLTQyYWItYTIyNi1hODI3NDk2NmNiMTUiLCJldmVudF9pZCI6IjdjYjdmNTk4LThiOTgtNDM1Mi04NWQ2LWMxNjkyMTkzZWM2NiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NTc4OTc3OTUsImV4cCI6MTY1NzkwMTM5NSwiaWF0IjoxNjU3ODk3Nzk1LCJqdGkiOiI3NjZiZWE2Ny0wMGU5LTQxMTctYWQ0Yi00ZDk2MGQ5MDhhOTciLCJ1c2VybmFtZSI6Ijk4N2MyYzdkLTE2MGItNDMxZi1hMzA3LTQ1NDZmMmMxMWZmNCJ9.A08Km77JzE9pDXgMiXYuxygKi336BSIYZac4pDTMdgkCw76rB5DeU-v4i_2auEiU8O_1k4LLRvTZ1wXgvtGB08QZyZSZiJFYuDiM-1jQFS992yDL69T6lVoS_Z_Q_nO56Zyi5kwE_8y_BOC73zOFaLR1XES30RvrnvP3PKvW2g6QU9nRby8ABCHjYPmRq8WWpSWHoyv_0nvwoVh8NAwzeyWJbra_ngNsODaG-gkfQFZb7QdCEB_-Ui0jmhKnE26OG9eHtH5ccoYmEfAsrnuThCHKcTg3CtBvwdU6G-vbQFrDxE0O6XN_FhxRKrv3QdeZGnZ9Ab-E3GizcriLRfXrOw'
REGION = os.environ.get('COGNITO_REGION_NAME')
USERPOOL_ID = os.environ.get('USER_POOL_ID')
APP_CLIENT_ID = os.environ.get('COGNITO_USER_CLIENT_ID')


verified_claims: dict = cognitojwt.decode(
    id_token,
    REGION,
    USERPOOL_ID,
    app_client_id=APP_CLIENT_ID  # Optional
    # testmode=False  # Disable token expiration check for testing purposes
)

print(verified_claims)