import os

import cognitojwt
from dotenv import load_dotenv
load_dotenv()

os.environ.get('COGNITO_REGION_NAME')

id_token = 'eyJraWQiOiJcL0Fia01US1h1UitIVmtsb0N2SE1PdVJ0NXJZZStvY1VxRThFNEJMeVNBdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxZGI0YjgwNS1kMzk3LTQ2OWYtYjZmMC04N2Q1ZGZlMjAyMTkiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9aaEhESllMNWMiLCJjbGllbnRfaWQiOiIybmx2NGdvMWpjMWE3ajV1ZXFiNWsxcnYxaSIsIm9yaWdpbl9qdGkiOiJmM2MzNjRhZi03NmQxLTQwNjMtOGQ3OC00MmUwYWM5OGU4YmMiLCJldmVudF9pZCI6IjdmMjkxNzgyLTQxODEtNDFiYy05OTQ2LTZjMzc3YmJhY2QwOSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NTc4OTcwMjIsImV4cCI6MTY1NzkwMDYyMiwiaWF0IjoxNjU3ODk3MDIyLCJqdGkiOiIxYjAwY2Y4MC0wZTMyLTQ5ZDEtOTExOS0zZjkwOWRiNDExNzEiLCJ1c2VybmFtZSI6IjFkYjRiODA1LWQzOTctNDY5Zi1iNmYwLTg3ZDVkZmUyMDIxOSJ9.Fo5sQjgfHqOE5PkHPc88c34D68vPYjMVLNXYwEDGElsryl-uBs5NkTk7i_3MmIT-K4oiDA9-bQdGRuWb5WOT_xzJEKSPHCRlrYTxKbxy7v0zW9H3Cp9a5s2fUOT7uXoFHseHimOijfI5O3syeJVDj6W2UP9zpBazEZGcIxM4O10VwXTrcyYjImfSwefrkD6WU-P1lMCyyeJ6JnCShvENLm2M9vih9kDWsCHQ72uUNtZiwQkomriFBQ3oEfr_ui5EBIbQPL12yhssUHmxLtWoXJDTeyKxdJnN5pn51otQzwsK5vCbooPTngwsiWDDyvvBlPIWP1DomJ6dOA_ZzlbXzw'
REGION = os.environ.get('COGNITO_REGION_NAME')
USERPOOL_ID = os.environ.get('USER_POOL_ID')
APP_CLIENT_ID = os.environ.get('COGNITO_USER_CLIENT_ID')

verified_claims: dict = cognitojwt.decode(
    id_token,
    REGION,
    USERPOOL_ID,
    app_client_id=APP_CLIENT_ID  # Optional
    # testmode=False  # Disable token expiration check for testing purposes
)

print(verified_claims)